<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151212173315.1"><vh>@settings</vh>
<v t="leo.20151212173315.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151212173315.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20160921213353.1"><vh>2016fall 簡報與網誌樣板系統</vh></v>
<v t="amd.20160106095324.1" a="E"><vh>@path ./../</vh>
<v t="leo.20151213173830.1" a="E"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20151213085727.1"><vh>@button pelican-blog</vh></v>
</v>
<v t="amd.20151215180106.1" a="E"><vh>設定與開發</vh>
<v t="amd.20151216151325.1"><vh>@@edit index.html</vh></v>
<v t="leo.20161014123150.1" a="E"><vh>@clean index.html</vh>
<v t="leo.20161014123150.2" a="E"><vh>html</vh>
<v t="leo.20161014123150.3"><vh>head</vh></v>
<v t="leo.20161014123150.4" a="E"><vh>body</vh>
<v t="leo.20161014123150.5" a="E"><vh>reveal div</vh>
<v t="leo.20161014123150.6" a="E"><vh>slides div</vh>
<v t="leo.20161014123150.7" a="E"><vh>封面投影片</vh>
<v t="leo.20161014123150.8"><vh>封面投影片內容</vh></v>
</v>
<v t="leo.20161014123150.9"><vh>三大主題教學</vh>
<v t="leo.20161014123150.10" a="E"><vh>主題教學</vh>
<v t="leo.20161014123150.11"><vh>電腦輔助設計在教什麼?</vh></v>
</v>
<v t="leo.20161014123150.12" a="E"><vh>主題教學內容</vh>
<v t="leo.20161014123150.13"><vh>電腦輔助設計在教什麼?</vh></v>
</v>
<v t="leo.20161014123150.14" a="E"><vh>相關課程</vh>
<v t="leo.20161014123150.15"><vh>電腦輔助設計系列課程</vh></v>
</v>
<v t="leo.20161014123150.16" a="E"><vh>創造力</vh>
<v t="leo.20161014123150.17"><vh>何謂創造力?</vh></v>
</v>
<v t="leo.20161014123150.18" a="E"><vh>創造力</vh>
<v t="leo.20161014123150.19"><vh>何謂創造力?</vh></v>
</v>
<v t="leo.20161014123150.20" a="E"><vh>所謂自學</vh>
<v t="leo.20161014123150.21"><vh>自學的訓練</vh></v>
</v>
<v t="leo.20161014123150.22" a="E"><vh>執行力</vh>
<v t="leo.20161014123150.23"><vh>高效執行力</vh></v>
</v>
</v>
<v t="leo.20161014123150.24"><vh>電腦輔助設計課程內涵</vh>
<v t="leo.20161014123150.25" a="E"><vh>電腦輔助設計課程內涵</vh>
<v t="leo.20161014123150.26"><vh>CAD 教學主題</vh></v>
</v>
<v t="leo.20161014123150.27"><vh>Github pages 網頁</vh>
<v t="leo.20161014123150.28"><vh>各學員任務</vh></v>
</v>
<v t="leo.20161014123150.29"><vh>所有操作都必須拍影片</vh>
<v t="leo.20161014123150.30"><vh>操作影片</vh></v>
</v>
<v t="leo.20161014123150.31"><vh>Solvespace 操作練習</vh>
<v t="leo.20161014123150.32"><vh>Solvespace 實習</vh></v>
</v>
<v t="leo.20161014123150.33"><vh>OnShape 操作練習</vh>
<v t="leo.20161014123150.34"><vh>OnShape 實習</vh></v>
</v>
<v t="leo.20161014123150.35"><vh>網際自評系統</vh>
<v t="leo.20161014123150.36"><vh>Flask 網際程式</vh></v>
</v>
</v>
<v t="leo.20161014123150.37" a="E"><vh>Windows 環境下可攜環境</vh>
<v t="leo.20161014123150.38" a="E"><vh>下載 miniconda 可攜環境</vh>
<v t="leo.20161014123150.39"><vh>下載可攜程式環境</vh></v>
</v>
</v>
<v t="leo.20161014123150.40"><vh>各式內容引用範例</vh>
<v t="leo.20161014123150.41" a="E"><vh>導入數學符號與方程式</vh>
<v t="leo.20161014123150.42"><vh>LaTeX 格式方程式</vh></v>
</v>
<v t="leo.20161014123150.43" a="E"><vh>導入縮排程式碼</vh>
<v t="leo.20161014123150.44"><vh>引用程式碼</vh></v>
</v>
<v t="leo.20161014123150.45" a="E"><vh>導入影片</vh>
<v t="leo.20161014123150.46"><vh>iframe 導入影片</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20151213230723.1" a="E"><vh>Pelican 設定</vh>
<v t="leo.20151213230957.1"><vh>文章 Date 設定</vh></v>
<v t="leo.20151213230729.1"><vh>使用 summary plugin</vh></v>
</v>
<v t="amd.20151215170117.1"><vh>以下 pelicanconf.py 為近端與遠端的共同設定</vh></v>
<v t="leo.20151212173725.1"><vh>@edit pelicanconf.py</vh></v>
<v t="amd.20151215170221.1"><vh>以下 local_publishconf.py 為近端所使用的設定</vh></v>
<v t="leo.20151213085752.1"><vh>@edit local_publishconf.py</vh></v>
<v t="amd.20151215121740.1"><vh>@path theme</vh>
<v t="amd.20151215154950.1" a="E"><vh>@path pelican-bootstrap3_local</vh>
<v t="amd.20151215154950.2" a="E"><vh>@path templates</vh>
<v t="amd.20151215154950.3"><vh>@edit base.html</vh></v>
<v t="amd.20151215154950.4"><vh>@edit search.html</vh></v>
<v t="amd.20151215162536.1" a="E"><vh>@path includes</vh>
<v t="amd.20151215162510.1"><vh>@edit sidebar.html</vh></v>
</v>
<v t="amd.20151215154950.5"><vh>@edit tags.html</vh></v>
</v>
</v>
</v>
<v t="amd.20151215170326.1"><vh>以下在修改或查驗 plugin 目錄下的檔案</vh></v>
<v t="amd.20151215154225.1"><vh>@path plugin</vh>
<v t="amd.20151215154238.1" a="E"><vh>@path tipue_search</vh>
<v t="amd.20151215154248.1"><vh>@edit tipue_search.py</vh></v>
</v>
</v>
<v t="amd.20160921225004.1"><vh>@edit .gitignore</vh></v>
</v>
</v>
<v t="amd.20151215170350.1"><vh>以下為 content 目錄中的 md 檔案</vh></v>
<v t="amd.20151216001126.1"><vh>md 檔案範例</vh></v>
<v t="amd.20151215170031.1" a="E"><vh>@path ./../content</vh>
<v t="amd.20160106093454.1" a="E"><vh>yen 所寫的網誌文章</vh>
<v t="amd.20160727114506.1" a="E"><vh>201609</vh>
<v t="amd.20160727120222.1"><vh>@edit 20160921.md</vh></v>
</v>
</v>
</v>
<v t="amd.20160106094754.1" a="E"><vh>@path ./../content/pages</vh>
<v t="amd.20160106094829.1" a="E"><vh>yen 所寫的 pages 文章</vh>
<v t="amd.20160106094844.1"><vh>@edit pages_1.md</vh></v>
</v>
</v>
<v t="leo.20161014123012.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20161014123012.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20161014123012.4"><vh>old:head</vh></v>
<v t="leo.20161014123012.5"><vh>new:head</vh></v>
</v>
<v t="leo.20161014123012.6"><vh>Recovered node "body" from @clean index.html</vh>
<v t="leo.20161014123013.1"><vh>old:body</vh></v>
<v t="leo.20161014123013.2"><vh>new:body</vh></v>
</v>
<v t="leo.20161014123013.3"><vh>Recovered node "reveal div" from @clean index.html</vh>
<v t="leo.20161014123013.4"><vh>old:reveal div</vh></v>
<v t="leo.20161014123013.5"><vh>new:reveal div</vh></v>
</v>
<v t="leo.20161014123013.6"><vh>Recovered node "slides div" from @clean index.html</vh>
<v t="leo.20161014123013.7"><vh>old:slides div</vh></v>
<v t="leo.20161014123013.8"><vh>new:slides div</vh></v>
</v>
<v t="leo.20161014123013.9"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20161014123013.10"><vh>old:封面投影片</vh></v>
<v t="leo.20161014123013.11"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20161014123013.12"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20161014123013.13"><vh>old:封面投影片內容</vh></v>
<v t="leo.20161014123013.14"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20161014123013.15"><vh>Recovered node "三大主題教學" from @clean index.html</vh>
<v t="leo.20161014123013.16"><vh>old:三大主題教學</vh></v>
<v t="leo.20161014123013.17"><vh>new:三大主題教學</vh></v>
</v>
<v t="leo.20161014123013.18"><vh>Recovered node "主題教學" from @clean index.html</vh>
<v t="leo.20161014123013.19"><vh>old:主題教學</vh></v>
<v t="leo.20161014123013.20"><vh>new:主題教學</vh></v>
</v>
<v t="leo.20161014123013.21"><vh>Recovered node "電腦輔助設計在教什麼?" from @clean index.html</vh>
<v t="leo.20161014123013.22"><vh>old:電腦輔助設計在教什麼?</vh></v>
<v t="leo.20161014123013.23"><vh>new:電腦輔助設計在教什麼?</vh></v>
</v>
<v t="leo.20161014123013.24"><vh>Recovered node "主題教學內容" from @clean index.html</vh>
<v t="leo.20161014123013.25"><vh>old:主題教學內容</vh></v>
<v t="leo.20161014123013.26"><vh>new:主題教學內容</vh></v>
</v>
<v t="leo.20161014123013.27"><vh>Recovered node "電腦輔助設計在教什麼?" from @clean index.html</vh>
<v t="leo.20161014123013.28"><vh>old:電腦輔助設計在教什麼?</vh></v>
<v t="leo.20161014123013.29"><vh>new:電腦輔助設計在教什麼?</vh></v>
</v>
<v t="leo.20161014123013.30"><vh>Recovered node "相關課程" from @clean index.html</vh>
<v t="leo.20161014123013.31"><vh>old:相關課程</vh></v>
<v t="leo.20161014123013.32"><vh>new:相關課程</vh></v>
</v>
<v t="leo.20161014123013.33"><vh>Recovered node "電腦輔助設計系列課程" from @clean index.html</vh>
<v t="leo.20161014123013.34"><vh>old:電腦輔助設計系列課程</vh></v>
<v t="leo.20161014123013.35"><vh>new:電腦輔助設計系列課程</vh></v>
</v>
<v t="leo.20161014123013.36"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161014123013.37"><vh>old:創造力</vh></v>
<v t="leo.20161014123013.38"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161014123013.39"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161014123013.40"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161014123013.41"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161014123013.42"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161014123013.43"><vh>old:創造力</vh></v>
<v t="leo.20161014123013.44"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161014123013.45"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161014123013.46"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161014123013.47"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161014123013.48"><vh>Recovered node "所謂自學" from @clean index.html</vh>
<v t="leo.20161014123013.49"><vh>old:所謂自學</vh></v>
<v t="leo.20161014123013.50"><vh>new:所謂自學</vh></v>
</v>
<v t="leo.20161014123013.51"><vh>Recovered node "自學的訓練" from @clean index.html</vh>
<v t="leo.20161014123013.52"><vh>old:自學的訓練</vh></v>
<v t="leo.20161014123013.53"><vh>new:自學的訓練</vh></v>
</v>
<v t="leo.20161014123013.54"><vh>Recovered node "執行力" from @clean index.html</vh>
<v t="leo.20161014123013.55"><vh>old:執行力</vh></v>
<v t="leo.20161014123013.56"><vh>new:執行力</vh></v>
</v>
<v t="leo.20161014123013.57"><vh>Recovered node "高效執行力" from @clean index.html</vh>
<v t="leo.20161014123013.58"><vh>old:高效執行力</vh></v>
<v t="leo.20161014123013.59"><vh>new:高效執行力</vh></v>
</v>
<v t="leo.20161014123013.60"><vh>Recovered node "電腦輔助設計課程內涵" from @clean index.html</vh>
<v t="leo.20161014123013.61"><vh>old:電腦輔助設計課程內涵</vh></v>
<v t="leo.20161014123013.62"><vh>new:電腦輔助設計課程內涵</vh></v>
</v>
<v t="leo.20161014123013.63"><vh>Recovered node "電腦輔助設計課程內涵" from @clean index.html</vh>
<v t="leo.20161014123013.64"><vh>old:電腦輔助設計課程內涵</vh></v>
<v t="leo.20161014123013.65"><vh>new:電腦輔助設計課程內涵</vh></v>
</v>
<v t="leo.20161014123013.66"><vh>Recovered node "CAD 教學主題" from @clean index.html</vh>
<v t="leo.20161014123013.67"><vh>old:CAD 教學主題</vh></v>
<v t="leo.20161014123013.68"><vh>new:CAD 教學主題</vh></v>
</v>
<v t="leo.20161014123013.69"><vh>Recovered node "Github pages 網頁" from @clean index.html</vh>
<v t="leo.20161014123013.70"><vh>old:Github pages 網頁</vh></v>
<v t="leo.20161014123013.71"><vh>new:Github pages 網頁</vh></v>
</v>
<v t="leo.20161014123013.72"><vh>Recovered node "各學員任務" from @clean index.html</vh>
<v t="leo.20161014123013.73"><vh>old:各學員任務</vh></v>
<v t="leo.20161014123013.74"><vh>new:各學員任務</vh></v>
</v>
<v t="leo.20161014123013.75"><vh>Recovered node "所有操作都必須拍影片" from @clean index.html</vh>
<v t="leo.20161014123013.76"><vh>old:所有操作都必須拍影片</vh></v>
<v t="leo.20161014123013.77"><vh>new:所有操作都必須拍影片</vh></v>
</v>
<v t="leo.20161014123013.78"><vh>Recovered node "操作影片" from @clean index.html</vh>
<v t="leo.20161014123013.79"><vh>old:操作影片</vh></v>
<v t="leo.20161014123013.80"><vh>new:操作影片</vh></v>
</v>
<v t="leo.20161014123013.81"><vh>Recovered node "Solvespace 操作練習" from @clean index.html</vh>
<v t="leo.20161014123013.82"><vh>old:Solvespace 操作練習</vh></v>
<v t="leo.20161014123013.83"><vh>new:Solvespace 操作練習</vh></v>
</v>
<v t="leo.20161014123013.84"><vh>Recovered node "Solvespace 實習" from @clean index.html</vh>
<v t="leo.20161014123013.85"><vh>old:Solvespace 實習</vh></v>
<v t="leo.20161014123013.86"><vh>new:Solvespace 實習</vh></v>
</v>
<v t="leo.20161014123013.87"><vh>Recovered node "OnShape 操作練習" from @clean index.html</vh>
<v t="leo.20161014123013.88"><vh>old:OnShape 操作練習</vh></v>
<v t="leo.20161014123013.89"><vh>new:OnShape 操作練習</vh></v>
</v>
<v t="leo.20161014123013.90"><vh>Recovered node "OnShape 實習" from @clean index.html</vh>
<v t="leo.20161014123013.91"><vh>old:OnShape 實習</vh></v>
<v t="leo.20161014123013.92"><vh>new:OnShape 實習</vh></v>
</v>
<v t="leo.20161014123013.93"><vh>Recovered node "網際自評系統" from @clean index.html</vh>
<v t="leo.20161014123013.94"><vh>old:網際自評系統</vh></v>
<v t="leo.20161014123013.95"><vh>new:網際自評系統</vh></v>
</v>
<v t="leo.20161014123013.96"><vh>Recovered node "Flask 網際程式" from @clean index.html</vh>
<v t="leo.20161014123013.97"><vh>old:Flask 網際程式</vh></v>
<v t="leo.20161014123013.98"><vh>new:Flask 網際程式</vh></v>
</v>
<v t="leo.20161014123013.99"><vh>Recovered node "Windows 環境下可攜環境" from @clean index.html</vh>
<v t="leo.20161014123013.100"><vh>old:Windows 環境下可攜環境</vh></v>
<v t="leo.20161014123013.101"><vh>new:Windows 環境下可攜環境</vh></v>
</v>
<v t="leo.20161014123013.102"><vh>Recovered node "下載 miniconda 可攜環境" from @clean index.html</vh>
<v t="leo.20161014123013.103"><vh>old:下載 miniconda 可攜環境</vh></v>
<v t="leo.20161014123013.104"><vh>new:下載 miniconda 可攜環境</vh></v>
</v>
<v t="leo.20161014123013.105"><vh>Recovered node "下載可攜程式環境" from @clean index.html</vh>
<v t="leo.20161014123013.106"><vh>old:下載可攜程式環境</vh></v>
<v t="leo.20161014123013.107"><vh>new:下載可攜程式環境</vh></v>
</v>
<v t="leo.20161014123013.108"><vh>Recovered node "各式內容引用範例" from @clean index.html</vh>
<v t="leo.20161014123013.109"><vh>old:各式內容引用範例</vh></v>
<v t="leo.20161014123013.110"><vh>new:各式內容引用範例</vh></v>
</v>
<v t="leo.20161014123013.111"><vh>Recovered node "導入數學符號與方程式" from @clean index.html</vh>
<v t="leo.20161014123013.112"><vh>old:導入數學符號與方程式</vh></v>
<v t="leo.20161014123013.113"><vh>new:導入數學符號與方程式</vh></v>
</v>
<v t="leo.20161014123013.114"><vh>Recovered node "LaTeX 格式方程式" from @clean index.html</vh>
<v t="leo.20161014123013.115"><vh>old:LaTeX 格式方程式</vh></v>
<v t="leo.20161014123013.116"><vh>new:LaTeX 格式方程式</vh></v>
</v>
<v t="leo.20161014123013.117"><vh>Recovered node "導入縮排程式碼" from @clean index.html</vh>
<v t="leo.20161014123013.118"><vh>old:導入縮排程式碼</vh></v>
<v t="leo.20161014123013.119"><vh>new:導入縮排程式碼</vh></v>
</v>
<v t="leo.20161014123013.120"><vh>Recovered node "引用程式碼" from @clean index.html</vh>
<v t="leo.20161014123013.121"><vh>old:引用程式碼</vh></v>
<v t="leo.20161014123013.122"><vh>new:引用程式碼</vh></v>
</v>
<v t="leo.20161014123013.123"><vh>Recovered node "導入影片" from @clean index.html</vh>
<v t="leo.20161014123013.124"><vh>old:導入影片</vh></v>
<v t="leo.20161014123013.125"><vh>new:導入影片</vh></v>
</v>
<v t="leo.20161014123013.126"><vh>Recovered node "iframe 導入影片" from @clean index.html</vh>
<v t="leo.20161014123013.127"><vh>old:iframe 導入影片</vh></v>
<v t="leo.20161014123013.128"><vh>new:iframe 導入影片</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20151215121740.1"></t>
<t tx="amd.20151215154225.1"></t>
<t tx="amd.20151215154238.1"></t>
<t tx="amd.20151215154950.1"></t>
<t tx="amd.20151215154950.2"></t>
<t tx="amd.20151215162536.1"></t>
<t tx="amd.20151215170031.1"></t>
<t tx="amd.20151215170117.1"></t>
<t tx="amd.20151215170221.1"></t>
<t tx="amd.20151215170326.1"></t>
<t tx="amd.20151215170350.1"></t>
<t tx="amd.20151215180106.1"></t>
<t tx="amd.20151216001126.1">@language md
Title: 文章標題 (請注意各文章的標題不可相同, 比較保險的作法是冠上四個學號尾碼)
Category: 類別
Tags: 標籤
Author: yen

這裡放入文章摘要

&lt;!-- PELICAN_END_SUMMARY --&gt;

這裡為文章主要內容

程式碼

&lt;pre class="brush: python;"&gt;
print("hello")
&lt;/pre&gt;</t>
<t tx="amd.20151216151325.1">@language html
&lt;!doctype html&gt;
&lt;html lang="en"&gt;

	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;

	&lt;body&gt;

		&lt;div class="reveal"&gt;

			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;github_intro&lt;/h2&gt;
&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;p&gt;&lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
				&lt;/section&gt;
				
                               &lt;section&gt;
					&lt;h2&gt;fork_pull_requests&lt;/h2&gt;
				&lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
&lt;p&gt;&lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
                              &lt;/section&gt;
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;h2&gt;Vertical Slides&lt;/h2&gt;
						&lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
						&lt;p&gt;Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 1&lt;/h2&gt;
						&lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Slides&lt;/h2&gt;
					&lt;p&gt;
						Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Point of View&lt;/h2&gt;
					&lt;p&gt;
						Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
					&lt;/p&gt;
					&lt;p&gt;
						Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Touch Optimized&lt;/h2&gt;
					&lt;p&gt;
						Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-markdown&gt;
					&lt;script type="text/template"&gt;
						## Markdown support

						Write content using inline or external Markdown.
						Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

						```
						&lt;section data-markdown&gt;
						  ## Markdown support

						  Write content using inline or external Markdown.
						  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
						&lt;/section&gt;
						```
					&lt;/script&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section id="fragments"&gt;
						&lt;h2&gt;Fragments&lt;/h2&gt;
						&lt;p&gt;Hit the next arrow...&lt;/p&gt;
						&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
						&lt;p&gt;&lt;span class="fragment"&gt;... a&lt;/span&gt; &lt;span class="fragment"&gt;fragmented&lt;/span&gt; &lt;span class="fragment"&gt;slide.&lt;/span&gt;&lt;/p&gt;

						&lt;aside class="notes"&gt;
							This slide has fragments which are also stepped through in the notes window.
						&lt;/aside&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section id="transitions"&gt;
					&lt;h2&gt;Transition Styles&lt;/h2&gt;
					&lt;p&gt;
						You can select from different transitions, like: &lt;br&gt;
						&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
						&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section id="themes"&gt;
					&lt;h2&gt;Themes&lt;/h2&gt;
					&lt;p&gt;
						reveal.js comes with a few themes built in: &lt;br&gt;
						&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; &lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						&lt;p&gt;
							Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
						&lt;/p&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs"&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
						&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
							&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
							&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
						&lt;/div&gt;
					&lt;/section&gt;
					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs"&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						You can override background transitions per-slide.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Pretty Code&lt;/h2&gt;
					&lt;pre&gt;&lt;code class="hljs" data-trim contenteditable&gt;
function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
					&lt;/code&gt;&lt;/pre&gt;
					&lt;p&gt;Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Marvelous List&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;No order here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					&lt;ol&gt;
						&lt;li&gt;One is smaller than...&lt;/li&gt;
						&lt;li&gt;Two is smaller than...&lt;/li&gt;
						&lt;li&gt;Three!&lt;/li&gt;
					&lt;/ol&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					&lt;table&gt;
						&lt;thead&gt;
							&lt;tr&gt;
								&lt;th&gt;Item&lt;/th&gt;
								&lt;th&gt;Value&lt;/th&gt;
								&lt;th&gt;Quantity&lt;/th&gt;
							&lt;/tr&gt;
						&lt;/thead&gt;
						&lt;tbody&gt;
							&lt;tr&gt;
								&lt;td&gt;Apples&lt;/td&gt;
								&lt;td&gt;$1&lt;/td&gt;
								&lt;td&gt;7&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Lemonade&lt;/td&gt;
								&lt;td&gt;$2&lt;/td&gt;
								&lt;td&gt;18&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Bread&lt;/td&gt;
								&lt;td&gt;$3&lt;/td&gt;
								&lt;td&gt;2&lt;/td&gt;
							&lt;/tr&gt;
						&lt;/tbody&gt;
					&lt;/table&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					&lt;p&gt;
						These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
					&lt;/p&gt;
					&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
					&lt;/blockquote&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					&lt;p&gt;
						You can link between slides internally,
						&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Speaker View&lt;/h2&gt;
					&lt;p&gt;There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.&lt;/p&gt;
					&lt;p&gt;Press the &lt;em&gt;S&lt;/em&gt; key to try it out.&lt;/p&gt;

					&lt;aside class="notes"&gt;
						Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
					&lt;/aside&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Export to PDF&lt;/h2&gt;
					&lt;p&gt;Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:&lt;/p&gt;
					&lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Global State&lt;/h2&gt;
					&lt;p&gt;
						Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and &lt;code&gt;"something"&lt;/code&gt;
						will be added as a class to the document element when the slide is open. This lets you
						apply broader style changes, like switching the page background.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-state="customevent"&gt;
					&lt;h2&gt;State Events&lt;/h2&gt;
					&lt;p&gt;
						Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Take a Moment&lt;/h2&gt;
					&lt;p&gt;
						Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Much more&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;Right-to-left support&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section style="text-align: left;"&gt;
					&lt;h1&gt;THE END&lt;/h1&gt;
					&lt;p&gt;
						- &lt;a href="http://slides.com"&gt;Try the online editor&lt;/a&gt; &lt;br&gt;
						- &lt;a href="https://github.com/hakimel/reveal.js"&gt;Source code &amp;amp; documentation&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

			&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	&lt;/body&gt;
&lt;/html&gt;
</t>
<t tx="amd.20160106093454.1"></t>
<t tx="amd.20160106094754.1"></t>
<t tx="amd.20160106094829.1"></t>
<t tx="amd.20160106095324.1"></t>
<t tx="amd.20160727114506.1"></t>
<t tx="amd.20160921213353.1"></t>
<t tx="leo.20151212173315.1"></t>
<t tx="leo.20151212173315.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151212173315.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151213085727.1">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o blog -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20151213173830.1"></t>
<t tx="leo.20151213230723.1"></t>
<t tx="leo.20151213230729.1">利用

&lt;!-- PELICAN_END_SUMMARY --&gt;

來界定 Summary 摘要內容

前提, 必須設定 

PLUGIN_PATHS = ['plugin']

與

PLUGINS = ['liquid_tags.notebook', 'summary']

並且從 https://github.com/getpelican/pelican-plugins

取得 summary plugin</t>
<t tx="leo.20151213230957.1"># 設定網誌以 md 檔案建立的 file system date 為準, 無需自行設定

DEFAULT_DATE = 'fs'</t>
<t tx="leo.20161014123012.2"></t>
<t tx="leo.20161014123012.3">(uncached) leo.20161014113502.3
Diff...
+ &lt;head&gt;
+     &lt;meta charset="utf-8"&gt;
+ &lt;title&gt;
+ 2016 Fall 電腦輔助設計實習課程
+ &lt;/title&gt;
+     &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
+     &lt;meta name="author" content="Hakim El Hattab"&gt;
+     
+     &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
+     &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
+     
+     &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
+     
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
+     
+     &lt;!-- Theme used for syntax highlighting of code --&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
- 	&lt;head&gt;
- 		&lt;meta charset="utf-8"&gt;
+     &lt;!-- Printing and PDF exports --&gt;
+     &lt;script&gt;
+         var link = document.createElement( 'link' );
+         link.rel = 'stylesheet';
+         link.type = 'text/css';
+         link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
+         document.getElementsByTagName( 'head' )[0].appendChild( link );
+     &lt;/script&gt;
  
- 		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;
+     &lt;!--[if lt IE 9]&gt;
+     &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
+     &lt;![endif]--&gt;
+ &lt;/head&gt;
  
- 		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
- 		&lt;meta name="author" content="Hakim El Hattab"&gt;
- 
- 		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
- 		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
- 
- 		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
- 
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
- 
- 		&lt;!-- Theme used for syntax highlighting of code --&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
- 
- 		&lt;!-- Printing and PDF exports --&gt;
- 		&lt;script&gt;
- 			var link = document.createElement( 'link' );
- 			link.rel = 'stylesheet';
- 			link.type = 'text/css';
- 			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
- 			document.getElementsByTagName( 'head' )[0].appendChild( link );
- 		&lt;/script&gt;
- 
- 		&lt;!--[if lt IE 9]&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
- 		&lt;![endif]--&gt;
- 	&lt;/head&gt;
</t>
<t tx="leo.20161014123012.4">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;
2016 Fall 電腦輔助設計實習課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20161014123012.5">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20161014123012.6">(uncached) leo.20161014113502.4
Diff...
+ &lt;body&gt;
+ @others
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ &lt;script&gt;
+         // More info https://github.com/hakimel/reveal.js#configuration
+         Reveal.initialize({
+             controls: true,
+             progress: true,
+             history: true,
+             center: true,
  
+             transition: 'slide', // none/fade/slide/convex/concave/zoom
- @others
- 				&lt;section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Vertical Slides&lt;/h2&gt;
- 						&lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
- 						&lt;p&gt;Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.&lt;/p&gt;
- 						&lt;br&gt;
- 						&lt;a href="#" class="navigate-down"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 1&lt;/h2&gt;
- 						&lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
- 						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
- 						&lt;br&gt;
- 						&lt;a href="#/2"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;h2&gt;Slides&lt;/h2&gt;
- 					&lt;p&gt;
- 						Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Point of View&lt;/h2&gt;
- 					&lt;p&gt;
- 						Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
- 					&lt;/p&gt;
- 					&lt;p&gt;
- 						Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Touch Optimized&lt;/h2&gt;
- 					&lt;p&gt;
- 						Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-markdown&gt;
- 					&lt;script type="text/template"&gt;
- 						## Markdown support
- 
- 						Write content using inline or external Markdown.
- 						Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
- 
- 						```
- 						&lt;section data-markdown&gt;
- 						  ## Markdown support
- 
- 						  Write content using inline or external Markdown.
- 						  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
- 						&lt;/section&gt;
- 						```
- 					&lt;/script&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;section id="fragments"&gt;
- 						&lt;h2&gt;Fragments&lt;/h2&gt;
- 						&lt;p&gt;Hit the next arrow...&lt;/p&gt;
- 						&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
- 						&lt;p&gt;&lt;span class="fragment"&gt;... a&lt;/span&gt; &lt;span class="fragment"&gt;fragmented&lt;/span&gt; &lt;span class="fragment"&gt;slide.&lt;/span&gt;&lt;/p&gt;
- 
- 						&lt;aside class="notes"&gt;
- 							This slide has fragments which are also stepped through in the notes window.
- 						&lt;/aside&gt;
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
- 						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
- 						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
- 						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
- 						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
- 						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
- 						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
- 						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section id="transitions"&gt;
- 					&lt;h2&gt;Transition Styles&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can select from different transitions, like: &lt;br&gt;
- 						&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
- 						&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
- 						&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
- 						&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
- 						&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
- 						&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section id="themes"&gt;
- 					&lt;h2&gt;Themes&lt;/h2&gt;
- 					&lt;p&gt;
- 						reveal.js comes with a few themes built in: &lt;br&gt;
- 						&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; &lt;br&gt;
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
- 						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;section data-background="#dddddd"&gt;
- 						&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
- 						&lt;p&gt;
- 							Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
- 						&lt;/p&gt;
- 						&lt;a href="#" class="navigate-down"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
- 						&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
- 						&lt;pre&gt;&lt;code class="hljs"&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
- 						&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
- 						&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
- 						&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
- 							&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
- 							&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 						&lt;/div&gt;
- 					&lt;/section&gt;
- 					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
- 						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
- 					&lt;h2&gt;Background Transitions&lt;/h2&gt;
- 					&lt;p&gt;
- 						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="hljs"&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
- 					&lt;h2&gt;Background Transitions&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can override background transitions per-slide.
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Pretty Code&lt;/h2&gt;
- 					&lt;pre&gt;&lt;code class="hljs" data-trim contenteditable&gt;
- function linkify( selector ) {
-   if( supports3DTransforms ) {
- 
-     var nodes = document.querySelectorAll( selector );
- 
-     for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
-       var node = nodes[i];
- 
-       if( !node.className ) {
-         node.className += ' roll';
-       }
-     }
-   }
- }
- 					&lt;/code&gt;&lt;/pre&gt;
- 					&lt;p&gt;Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Marvelous List&lt;/h2&gt;
- 					&lt;ul&gt;
- 						&lt;li&gt;No order here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 						&lt;li&gt;Or here&lt;/li&gt;
- 					&lt;/ul&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
- 					&lt;ol&gt;
- 						&lt;li&gt;One is smaller than...&lt;/li&gt;
- 						&lt;li&gt;Two is smaller than...&lt;/li&gt;
- 						&lt;li&gt;Three!&lt;/li&gt;
- 					&lt;/ol&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Tabular Tables&lt;/h2&gt;
- 					&lt;table&gt;
- 						&lt;thead&gt;
- 							&lt;tr&gt;
- 								&lt;th&gt;Item&lt;/th&gt;
- 								&lt;th&gt;Value&lt;/th&gt;
- 								&lt;th&gt;Quantity&lt;/th&gt;
- 							&lt;/tr&gt;
- 						&lt;/thead&gt;
- 						&lt;tbody&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Apples&lt;/td&gt;
- 								&lt;td&gt;$1&lt;/td&gt;
- 								&lt;td&gt;7&lt;/td&gt;
- 							&lt;/tr&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Lemonade&lt;/td&gt;
- 								&lt;td&gt;$2&lt;/td&gt;
- 								&lt;td&gt;18&lt;/td&gt;
- 							&lt;/tr&gt;
- 							&lt;tr&gt;
- 								&lt;td&gt;Bread&lt;/td&gt;
- 								&lt;td&gt;$3&lt;/td&gt;
- 								&lt;td&gt;2&lt;/td&gt;
- 							&lt;/tr&gt;
- 						&lt;/tbody&gt;
- 					&lt;/table&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Clever Quotes&lt;/h2&gt;
- 					&lt;p&gt;
- 						These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
- 						&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
- 					&lt;/p&gt;
- 					&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
- 						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
- 						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
- 					&lt;/blockquote&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
- 					&lt;p&gt;
- 						You can link between slides internally,
- 						&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Speaker View&lt;/h2&gt;
- 					&lt;p&gt;There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.&lt;/p&gt;
- 					&lt;p&gt;Press the &lt;em&gt;S&lt;/em&gt; key to try it out.&lt;/p&gt;
- 
- 					&lt;aside class="notes"&gt;
- 						Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
- 					&lt;/aside&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Export to PDF&lt;/h2&gt;
- 					&lt;p&gt;Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:&lt;/p&gt;
- 					&lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Global State&lt;/h2&gt;
- 					&lt;p&gt;
- 						Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and &lt;code&gt;"something"&lt;/code&gt;
- 						will be added as a class to the document element when the slide is open. This lets you
- 						apply broader style changes, like switching the page background.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section data-state="customevent"&gt;
- 					&lt;h2&gt;State Events&lt;/h2&gt;
- 					&lt;p&gt;
- 						Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
- 					&lt;/p&gt;
- 					&lt;pre&gt;&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
- Reveal.addEventListener( 'customevent', function() {
- 	console.log( '"customevent" has fired' );
- } );
- 					&lt;/code&gt;&lt;/pre&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Take a Moment&lt;/h2&gt;
- 					&lt;p&gt;
- 						Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section&gt;
- 					&lt;h2&gt;Much more&lt;/h2&gt;
- 					&lt;ul&gt;
- 						&lt;li&gt;Right-to-left support&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;&lt;/li&gt;
- 						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;&lt;/li&gt;
- 					&lt;/ul&gt;
- 				&lt;/section&gt;
- 
- 				&lt;section style="text-align: left;"&gt;
- 					&lt;h1&gt;THE END&lt;/h1&gt;
- 					&lt;p&gt;
- 						- &lt;a href="http://slides.com"&gt;Try the online editor&lt;/a&gt; &lt;br&gt;
- 						- &lt;a href="https://github.com/hakimel/reveal.js"&gt;Source code &amp;amp; documentation&lt;/a&gt;
- 					&lt;/p&gt;
- 				&lt;/section&gt;
- 
- 			&lt;/div&gt;
- 
- 		&lt;/div&gt;
- 
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
- 
- 		&lt;script&gt;
- 
- 			// More info https://github.com/hakimel/reveal.js#configuration
- 			Reveal.initialize({
- 				controls: true,
- 				progress: true,
- 				history: true,
- 				center: true,
- 
- 				transition: 'slide', // none/fade/slide/convex/concave/zoom
- 
- 				// More info https://github.com/hakimel/reveal.js#dependencies
? ^^^^
+             // More info https://github.com/hakimel/reveal.js#dependencies
? ^^^^^^^^^^^^
- 				dependencies: [
+             dependencies: [
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
? ^^^^^^^^^^^^^^^^
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
? ^^^^^
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
? ^^^^^^^^^^^^^^^^                                                                                          +
- 				]
- 			});
- 
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
+             ]
+         });
- 		&lt;/script&gt;
? --
+ &lt;/script&gt;
- 
- 	&lt;/body&gt;
? -
+ &lt;/body&gt;
</t>
<t tx="leo.20161014123013.1">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20161014123013.10">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.100">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123013.101">@others
</t>
<t tx="leo.20161014123013.102">(uncached) leo.20161014113502.38
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.103">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.104">@others
</t>
<t tx="leo.20161014123013.105">(uncached) leo.20161014113502.39
Diff...
+ ## 下載 miniconda 可攜環境
+ 
+   * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
+   * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
+   * start.bat 啟動, stop.bat 關閉
+   * 建議存在隨身硬碟中使用
+ 
+ 
</t>
<t tx="leo.20161014123013.106">## 下載 miniconda 可攜環境

  * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
  * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
  * start.bat 啟動, stop.bat 關閉
  * 建議存在隨身硬碟中使用


</t>
<t tx="leo.20161014123013.107"></t>
<t tx="leo.20161014123013.108">(uncached) leo.20161014113502.40
Diff...
+ &lt;section&gt;
  @others
- 				&lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;/section&gt;</t>
<t tx="leo.20161014123013.109">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123013.11">
			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
@others
</t>
<t tx="leo.20161014123013.110">@others
				&lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014123013.111">(uncached) leo.20161014113502.41
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.112">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161014123013.113">@others
</t>
<t tx="leo.20161014123013.114">(uncached) leo.20161014113502.42
Diff...
+ # 數學符號與方程式
+ 
+ Inline math equations go in like so: $\omega = d\phi / dt$. Display
+ math should get its own line and be put in in double-dollarsigns:
+ 
+ $$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161014123013.115"># 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161014123013.116"></t>
<t tx="leo.20161014123013.117">(uncached) leo.20161014113502.43
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.118">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161014123013.119">@others
</t>
<t tx="leo.20161014123013.12">(uncached) leo.20161014113502.8
Diff...
+ ## 2016Fall 電腦輔助設計實習課程
- 			&lt;div class="slides"&gt;
- 				&lt;section&gt;
- 					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
- 					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
- 					&lt;p&gt;
- 						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
- 					&lt;/p&gt;
-                     &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;h2&gt;github_intro&lt;/h2&gt;
+ ### 虎科大機械設計工程系
+ 
+ &lt;small&gt;
+ Created by [BG1](http://chiamingyen.github.io/kmolab/blog/)
+ &lt;/small&gt;
+ 
+ [甲班電腦輔助設計實習課程網誌](blog/index.html)
+ 
+ [乙班電腦輔助設計實習課程網誌](https://mdecourse.github.io/2016fallcadpb/blog)
+ 
+ [Vimeo 上課影片](https://vimeo.com/user24079973/videos)
</t>
<t tx="leo.20161014123013.120">(uncached) leo.20161014113502.44
Diff...
+ ## 利用 Markdown 寫投影片
+ 以下利用 Markdown 格式展示 Python 程式碼:
+ ```
  @language python
+ # use threading and subprocess to threading the make process
+ import os
+ import subprocess
+ import threading
+ 
+ def domake():
+     
+     path = "../exposed/api/exposed"
+     ubuntu = "../Ubuntu"
+     
+     # create obj path
+     
+     if not os.path.exists(path+"/../obj"):
+         os.makedirs(path+"/../obj")
+     
+     subprocess.call(["make", "clean"], cwd=path)
+     subprocess.call("make", cwd=path)
+     subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
+     subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
+     
+ make = threading.Thread(target=domake)
+ make.start()
+ ```
</t>
<t tx="leo.20161014123013.121">## 利用 Markdown 寫投影片
以下利用 Markdown 格式展示 Python 程式碼:
```
@language python
# use threading and subprocess to threading the make process
import os
import subprocess
import threading

def domake():
    
    path = "../exposed/api/exposed"
    ubuntu = "../Ubuntu"
    
    # create obj path
    
    if not os.path.exists(path+"/../obj"):
        os.makedirs(path+"/../obj")
    
    subprocess.call(["make", "clean"], cwd=path)
    subprocess.call("make", cwd=path)
    subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
    subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
    
make = threading.Thread(target=domake)
make.start()
```
</t>
<t tx="leo.20161014123013.122">@language python
</t>
<t tx="leo.20161014123013.123">(uncached) leo.20161014113502.45
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- &lt;p&gt;&lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
+     &lt;/script&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
+ 
+ 
- 				
+ 						
? ++
-                                &lt;section&gt;
- 					&lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20161014123013.124">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.125">@others
&lt;p&gt;&lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
				&lt;/section&gt;
				
                               &lt;section&gt;
					&lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20161014123013.126">(uncached) leo.20161014113502.46
Diff...
+ ## 使用 iframe 導入影片
+ 
+ ### 導入影片 template
+ 
  &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014123013.127">## 使用 iframe 導入影片

### 導入影片 template

&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014123013.128">&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014123013.13">## 2016Fall 電腦輔助設計實習課程

### 虎科大機械設計工程系

&lt;small&gt;
Created by [BG1](http://chiamingyen.github.io/kmolab/blog/)
&lt;/small&gt;

[甲班電腦輔助設計實習課程網誌](blog/index.html)

[乙班電腦輔助設計實習課程網誌](https://mdecourse.github.io/2016fallcadpb/blog)

[Vimeo 上課影片](https://vimeo.com/user24079973/videos)
</t>
<t tx="leo.20161014123013.14">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;2016Fall CPA 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;github_intro&lt;/h2&gt;
</t>
<t tx="leo.20161014123013.15">(uncached) leo.20161014113502.9
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;
</t>
<t tx="leo.20161014123013.16">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20161014123013.17">@others
</t>
<t tx="leo.20161014123013.18">(uncached) leo.20161014113502.10
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.2">
@others
				&lt;section&gt;
					&lt;section&gt;
						&lt;h2&gt;Vertical Slides&lt;/h2&gt;
						&lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
						&lt;p&gt;Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 1&lt;/h2&gt;
						&lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Slides&lt;/h2&gt;
					&lt;p&gt;
						Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Point of View&lt;/h2&gt;
					&lt;p&gt;
						Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
					&lt;/p&gt;
					&lt;p&gt;
						Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Touch Optimized&lt;/h2&gt;
					&lt;p&gt;
						Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-markdown&gt;
					&lt;script type="text/template"&gt;
						## Markdown support

						Write content using inline or external Markdown.
						Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

						```
						&lt;section data-markdown&gt;
						  ## Markdown support

						  Write content using inline or external Markdown.
						  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
						&lt;/section&gt;
						```
					&lt;/script&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section id="fragments"&gt;
						&lt;h2&gt;Fragments&lt;/h2&gt;
						&lt;p&gt;Hit the next arrow...&lt;/p&gt;
						&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
						&lt;p&gt;&lt;span class="fragment"&gt;... a&lt;/span&gt; &lt;span class="fragment"&gt;fragmented&lt;/span&gt; &lt;span class="fragment"&gt;slide.&lt;/span&gt;&lt;/p&gt;

						&lt;aside class="notes"&gt;
							This slide has fragments which are also stepped through in the notes window.
						&lt;/aside&gt;
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section id="transitions"&gt;
					&lt;h2&gt;Transition Styles&lt;/h2&gt;
					&lt;p&gt;
						You can select from different transitions, like: &lt;br&gt;
						&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
						&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section id="themes"&gt;
					&lt;h2&gt;Themes&lt;/h2&gt;
					&lt;p&gt;
						reveal.js comes with a few themes built in: &lt;br&gt;
						&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; &lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','https://cad-lab.github.io/cadlab_data/reveal/css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						&lt;p&gt;
							Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
						&lt;/p&gt;
						&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs"&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
						&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
					&lt;/section&gt;
					&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
							&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
							&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
						&lt;/div&gt;
					&lt;/section&gt;
					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs"&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					&lt;h2&gt;Background Transitions&lt;/h2&gt;
					&lt;p&gt;
						You can override background transitions per-slide.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="hljs" style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Pretty Code&lt;/h2&gt;
					&lt;pre&gt;&lt;code class="hljs" data-trim contenteditable&gt;
function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
					&lt;/code&gt;&lt;/pre&gt;
					&lt;p&gt;Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Marvelous List&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;No order here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
						&lt;li&gt;Or here&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					&lt;ol&gt;
						&lt;li&gt;One is smaller than...&lt;/li&gt;
						&lt;li&gt;Two is smaller than...&lt;/li&gt;
						&lt;li&gt;Three!&lt;/li&gt;
					&lt;/ol&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					&lt;table&gt;
						&lt;thead&gt;
							&lt;tr&gt;
								&lt;th&gt;Item&lt;/th&gt;
								&lt;th&gt;Value&lt;/th&gt;
								&lt;th&gt;Quantity&lt;/th&gt;
							&lt;/tr&gt;
						&lt;/thead&gt;
						&lt;tbody&gt;
							&lt;tr&gt;
								&lt;td&gt;Apples&lt;/td&gt;
								&lt;td&gt;$1&lt;/td&gt;
								&lt;td&gt;7&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Lemonade&lt;/td&gt;
								&lt;td&gt;$2&lt;/td&gt;
								&lt;td&gt;18&lt;/td&gt;
							&lt;/tr&gt;
							&lt;tr&gt;
								&lt;td&gt;Bread&lt;/td&gt;
								&lt;td&gt;$3&lt;/td&gt;
								&lt;td&gt;2&lt;/td&gt;
							&lt;/tr&gt;
						&lt;/tbody&gt;
					&lt;/table&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					&lt;p&gt;
						These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
					&lt;/p&gt;
					&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
					&lt;/blockquote&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					&lt;p&gt;
						You can link between slides internally,
						&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Speaker View&lt;/h2&gt;
					&lt;p&gt;There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.&lt;/p&gt;
					&lt;p&gt;Press the &lt;em&gt;S&lt;/em&gt; key to try it out.&lt;/p&gt;

					&lt;aside class="notes"&gt;
						Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
					&lt;/aside&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Export to PDF&lt;/h2&gt;
					&lt;p&gt;Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:&lt;/p&gt;
					&lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Global State&lt;/h2&gt;
					&lt;p&gt;
						Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and &lt;code&gt;"something"&lt;/code&gt;
						will be added as a class to the document element when the slide is open. This lets you
						apply broader style changes, like switching the page background.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section data-state="customevent"&gt;
					&lt;h2&gt;State Events&lt;/h2&gt;
					&lt;p&gt;
						Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
					&lt;/p&gt;
					&lt;pre&gt;&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Take a Moment&lt;/h2&gt;
					&lt;p&gt;
						Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
					&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;Much more&lt;/h2&gt;
					&lt;ul&gt;
						&lt;li&gt;Right-to-left support&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/section&gt;

				&lt;section style="text-align: left;"&gt;
					&lt;h1&gt;THE END&lt;/h1&gt;
					&lt;p&gt;
						- &lt;a href="http://slides.com"&gt;Try the online editor&lt;/a&gt; &lt;br&gt;
						- &lt;a href="https://github.com/hakimel/reveal.js"&gt;Source code &amp;amp; documentation&lt;/a&gt;
					&lt;/p&gt;
				&lt;/section&gt;

			&lt;/div&gt;

		&lt;/div&gt;

		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20161014123013.20">@others
</t>
<t tx="leo.20161014123013.21">(uncached) leo.20161014113502.11
Diff...
+ ## 電腦輔助設計在教什麼?
+ 
+ ### 創造力
+ ### 表達力
+ 以及
+ ### 協同力
+ 
</t>
<t tx="leo.20161014123013.22">## 電腦輔助設計在教什麼?

### 創造力
### 表達力
以及
### 協同力

</t>
<t tx="leo.20161014123013.23"></t>
<t tx="leo.20161014123013.24">(uncached) leo.20161014113502.12
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.26">@others
</t>
<t tx="leo.20161014123013.27">(uncached) leo.20161014113502.13
Diff...
+ # CAD 在教什麼?
+ 
+ ## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
+ ## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
+ &lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
+ ## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;
+ 
</t>
<t tx="leo.20161014123013.28"># CAD 在教什麼?

## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
&lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;

</t>
<t tx="leo.20161014123013.29"></t>
<t tx="leo.20161014123013.3">(uncached) leo.20161014113502.5
Diff...
- 	&lt;body&gt;
+ &lt;div class="reveal"&gt;
  @others
-                               
- 				&lt;!-- Example of nested vertical slides --&gt;
+ &lt;/div&gt;
+ 
</t>
<t tx="leo.20161014123013.30">(uncached) leo.20161014113502.14
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.32">@others
</t>
<t tx="leo.20161014123013.33">(uncached) leo.20161014113502.15
Diff...
+ # CAD 系列課程
+ 
+ ## 計算機程式
+ ## 網際內容管理
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 協同產品設計實習
+ 也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;
+ 
</t>
<t tx="leo.20161014123013.34"># CAD 系列課程

## 計算機程式
## 網際內容管理
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 協同產品設計實習
也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;

</t>
<t tx="leo.20161014123013.35"></t>
<t tx="leo.20161014123013.36">(uncached) leo.20161014113502.16
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.37">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.38">@others
</t>
<t tx="leo.20161014123013.39">(uncached) leo.20161014113502.17
Diff...
+ # 何謂創造力?
+ 
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;
+ 
</t>
<t tx="leo.20161014123013.4">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161014123013.40"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;

</t>
<t tx="leo.20161014123013.41"></t>
<t tx="leo.20161014123013.42">(uncached) leo.20161014113502.18
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.43">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.44">@others
</t>
<t tx="leo.20161014123013.45">(uncached) leo.20161014113502.19
Diff...
+ # 何謂創造力?
+ 
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;
+ 
</t>
<t tx="leo.20161014123013.46"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;

</t>
<t tx="leo.20161014123013.47"></t>
<t tx="leo.20161014123013.48">(uncached) leo.20161014113502.20
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.49">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.5">	&lt;body&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
</t>
<t tx="leo.20161014123013.50">@others
</t>
<t tx="leo.20161014123013.51">(uncached) leo.20161014113502.21
Diff...
+ # 自學的訓練
+ 
+ ## 學員必須自己有學習動機
+ ## 能消化中英文資料
+ ## 從中體會學習的意義
+ 
+ 
</t>
<t tx="leo.20161014123013.52"># 自學的訓練

## 學員必須自己有學習動機
## 能消化中英文資料
## 從中體會學習的意義


</t>
<t tx="leo.20161014123013.53"></t>
<t tx="leo.20161014123013.54">(uncached) leo.20161014113502.22
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.55">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.56">@others
</t>
<t tx="leo.20161014123013.57">(uncached) leo.20161014113502.23
Diff...
+ # 高效執行力
+ 
+ ## 用對的方法
+ ## 在對的時機
+ ## 找對的人
+ ## 作對的事
+ 
+ 
</t>
<t tx="leo.20161014123013.58"># 高效執行力

## 用對的方法
## 在對的時機
## 找對的人
## 作對的事


</t>
<t tx="leo.20161014123013.59"></t>
<t tx="leo.20161014123013.6">(uncached) leo.20161014113502.6
Diff...
+ &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
+ &lt;div class="slides"&gt;
+ @others
+ &lt;/div&gt;
  
- 		&lt;div class="reveal"&gt;
- @others
- &lt;p&gt;&lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
-                               &lt;/section&gt;
</t>
<t tx="leo.20161014123013.60">(uncached) leo.20161014113502.24
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161014123013.61">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123013.62">@others
</t>
<t tx="leo.20161014123013.63">(uncached) leo.20161014113502.25
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.64">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.65">@others
</t>
<t tx="leo.20161014123013.66">(uncached) leo.20161014113502.26
Diff...
+ ## 電腦輔助設計實習課程
+ 
+ 教學主題
+ 
+   * 課程網頁、學員網頁、分組網頁串連
+   * Solvespace 零組件繪圖與機構模擬
+   * OnShape 零組件繪圖與機構模擬
+   * Delta 3D printer 零組件繪圖與模擬
+   * Delta 3D printer 零組件列印組立
+   * 建立網際自評系統
+ 
+ 
</t>
<t tx="leo.20161014123013.67">## 電腦輔助設計實習課程

教學主題

  * 課程網頁、學員網頁、分組網頁串連
  * Solvespace 零組件繪圖與機構模擬
  * OnShape 零組件繪圖與機構模擬
  * Delta 3D printer 零組件繪圖與模擬
  * Delta 3D printer 零組件列印組立
  * 建立網際自評系統


</t>
<t tx="leo.20161014123013.68"></t>
<t tx="leo.20161014123013.69">(uncached) leo.20161014113502.27
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.7">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161014123013.70">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.71">@others
</t>
<t tx="leo.20161014123013.72">(uncached) leo.20161014113502.28
Diff...
+ ## Github Pages 網頁
+ 
+ 各學員必須完成
+ 
+   * 個人網頁
+   * Solvespace 零組件繪圖與機構模擬
+   * OnShape 零組件繪圖與機構模擬
+   * Delta 3D printer 零組件繪圖與模擬
+   * 利用 Delta 3D printer 列印零組件並組立
+   * 建立網際自評系統
</t>
<t tx="leo.20161014123013.73">## Github Pages 網頁

各學員必須完成

  * 個人網頁
  * Solvespace 零組件繪圖與機構模擬
  * OnShape 零組件繪圖與機構模擬
  * Delta 3D printer 零組件繪圖與模擬
  * 利用 Delta 3D printer 列印零組件並組立
  * 建立網際自評系統
</t>
<t tx="leo.20161014123013.74"></t>
<t tx="leo.20161014123013.75">(uncached) leo.20161014113502.29
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.76">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.77">@others
</t>
<t tx="leo.20161014123013.78">(uncached) leo.20161014113502.30
Diff...
+ ## 操作影片錄製
+ 
+   * Windows 環境下使用 ShareX
+   * Ubuntu 環境下使用 Kazam
+   * 影片檔岸上傳到 Vimeo
+   * 影片檔案上傳到 Youtube
+   * 在投影片與網誌中嵌入影片檔
</t>
<t tx="leo.20161014123013.79">## 操作影片錄製

  * Windows 環境下使用 ShareX
  * Ubuntu 環境下使用 Kazam
  * 影片檔岸上傳到 Vimeo
  * 影片檔案上傳到 Youtube
  * 在投影片與網誌中嵌入影片檔
</t>
<t tx="leo.20161014123013.8">
		&lt;div class="reveal"&gt;
@others
&lt;p&gt;&lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
                              &lt;/section&gt;
</t>
<t tx="leo.20161014123013.80"></t>
<t tx="leo.20161014123013.81">(uncached) leo.20161014113502.31
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.82">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.83">@others
</t>
<t tx="leo.20161014123013.84">(uncached) leo.20161014113502.32
Diff...
+ ## Solvespace 實習
+ 
+   * Solvespace 零件繪製
+   * Solvespace 零件組立
+   * Delta 3D Printer 機構模擬
+   * 平面四連桿機構模擬與驗證
+   * 平面多連桿機構模擬與驗證
+   * Solvespace 程式編譯
</t>
<t tx="leo.20161014123013.85">## Solvespace 實習

  * Solvespace 零件繪製
  * Solvespace 零件組立
  * Delta 3D Printer 機構模擬
  * 平面四連桿機構模擬與驗證
  * 平面多連桿機構模擬與驗證
  * Solvespace 程式編譯
</t>
<t tx="leo.20161014123013.86"></t>
<t tx="leo.20161014123013.87">(uncached) leo.20161014113502.33
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.88">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.89">@others
</t>
<t tx="leo.20161014123013.9">(uncached) leo.20161014113502.7
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- 			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
- @others
+ 
+ 						
</t>
<t tx="leo.20161014123013.90">(uncached) leo.20161014113502.34
Diff...
+ ## OnShape 實習
+ 
+   * OnShape 零件繪製
+   * OnShape 零件組立
+   * Delta 3D Printer 機構模擬
+   * 平面四連桿機構模擬與驗證
+   * 平面多連桿機構模擬與驗證
+   * Featurescript 範例操作
</t>
<t tx="leo.20161014123013.91">## OnShape 實習

  * OnShape 零件繪製
  * OnShape 零件組立
  * Delta 3D Printer 機構模擬
  * 平面四連桿機構模擬與驗證
  * 平面多連桿機構模擬與驗證
  * Featurescript 範例操作
</t>
<t tx="leo.20161014123013.92"></t>
<t tx="leo.20161014123013.93">(uncached) leo.20161014113502.35
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161014123013.94">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123013.95">@others
</t>
<t tx="leo.20161014123013.96">(uncached) leo.20161014113502.36
Diff...
+ ## Flask 網際程式
+ 
+   * 以 CMSimfly 為例
+   * 以 PyGrouf 為例
+   * 以 Jupyterhub 為例
</t>
<t tx="leo.20161014123013.97">## Flask 網際程式

  * 以 CMSimfly 為例
  * 以 PyGrouf 為例
  * 以 Jupyterhub 為例
</t>
<t tx="leo.20161014123013.98"></t>
<t tx="leo.20161014123013.99">(uncached) leo.20161014113502.37
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161014123150.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20161014123150.10">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.11">## 電腦輔助設計在教什麼?

### 創造力
### 表達力
以及
### 協同力

</t>
<t tx="leo.20161014123150.12">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.13"># CAD 在教什麼?

## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
&lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;

</t>
<t tx="leo.20161014123150.14">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.15"># CAD 系列課程

## 計算機程式
## 網際內容管理
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 協同產品設計實習
也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;

</t>
<t tx="leo.20161014123150.16">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.17"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;

</t>
<t tx="leo.20161014123150.18">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.19"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;

</t>
<t tx="leo.20161014123150.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;
</t>
<t tx="leo.20161014123150.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.21"># 自學的訓練

## 學員必須自己有學習動機
## 能消化中英文資料
## 從中體會學習的意義


</t>
<t tx="leo.20161014123150.22">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.23"># 高效執行力

## 用對的方法
## 在對的時機
## 找對的人
## 作對的事


</t>
<t tx="leo.20161014123150.24">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123150.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.26">## 電腦輔助設計實習課程

教學主題

  * 課程網頁、學員網頁、分組網頁串連
  * Solvespace 零組件繪圖與機構模擬
  * OnShape 零組件繪圖與機構模擬
  * Delta 3D printer 零組件繪圖與模擬
  * Delta 3D printer 零組件列印組立
  * 建立網際自評系統


</t>
<t tx="leo.20161014123150.27">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.28">## Github Pages 網頁

各學員必須完成

  * 個人網頁
  * Solvespace 零組件繪圖與機構模擬
  * OnShape 零組件繪圖與機構模擬
  * Delta 3D printer 零組件繪圖與模擬
  * 利用 Delta 3D printer 列印零組件並組立
  * 建立網際自評系統
</t>
<t tx="leo.20161014123150.29">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.3">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;
2016 Fall 電腦輔助設計實習課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20161014123150.30">## 操作影片錄製

  * Windows 環境下使用 ShareX
  * Ubuntu 環境下使用 Kazam
  * 影片檔岸上傳到 Vimeo
  * 影片檔案上傳到 Youtube
  * 在投影片與網誌中嵌入影片檔
</t>
<t tx="leo.20161014123150.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.32">## Solvespace 實習

  * Solvespace 零件繪製
  * Solvespace 零件組立
  * Delta 3D Printer 機構模擬
  * 平面四連桿機構模擬與驗證
  * 平面多連桿機構模擬與驗證
  * Solvespace 程式編譯
</t>
<t tx="leo.20161014123150.33">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.34">## OnShape 實習

  * OnShape 零件繪製
  * OnShape 零件組立
  * Delta 3D Printer 機構模擬
  * 平面四連桿機構模擬與驗證
  * 平面多連桿機構模擬與驗證
  * Featurescript 範例操作
</t>
<t tx="leo.20161014123150.35">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.36">## Flask 網際程式

  * 以 CMSimfly 為例
  * 以 PyGrouf 為例
  * 以 Jupyterhub 為例
</t>
<t tx="leo.20161014123150.37">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123150.38">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.39">## 下載 miniconda 可攜環境

  * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
  * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
  * start.bat 啟動, stop.bat 關閉
  * 建議存在隨身硬碟中使用


</t>
<t tx="leo.20161014123150.4">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20161014123150.40">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161014123150.41">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161014123150.42"># 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161014123150.43">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161014123150.44">## 利用 Markdown 寫投影片
以下利用 Markdown 格式展示 Python 程式碼:
```
@language python
# use threading and subprocess to threading the make process
import os
import subprocess
import threading

def domake():
    
    path = "../exposed/api/exposed"
    ubuntu = "../Ubuntu"
    
    # create obj path
    
    if not os.path.exists(path+"/../obj"):
        os.makedirs(path+"/../obj")
    
    subprocess.call(["make", "clean"], cwd=path)
    subprocess.call("make", cwd=path)
    subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
    subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
    
make = threading.Thread(target=domake)
make.start()
```
</t>
<t tx="leo.20161014123150.45">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.46">## 使用 iframe 導入影片

### 導入影片 template

&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014123150.5">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161014123150.6">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20161014123150.7">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161014123150.8">## 2016Fall 電腦輔助設計實習課程

### 虎科大機械設計工程系

&lt;small&gt;
Created by [BG1](http://chiamingyen.github.io/kmolab/blog/)
&lt;/small&gt;

[甲班電腦輔助設計實習課程網誌](blog/index.html)

[乙班電腦輔助設計實習課程網誌](https://mdecourse.github.io/2016fallcadpb/blog)

[Vimeo 上課影片](https://vimeo.com/user24079973/videos)
</t>
<t tx="leo.20161014123150.9">&lt;section&gt;
@others
&lt;/section&gt;
</t>
</tnodes>
</leo_file>
